#!/bin/bash
python3 train_torcs.py \
    --save-path planner_5_seg_cont \
    --continuous \
    --planner \
    --use-seg \
    --num-total-act 2 \
    --pred-step 5 \
    --use-collision \
    --use-offroad \
    --use-distance \
    --use-pos \
    --sample-with-collision \
    --sample-with-offroad \
    --sample-with-pos \
    --sample-with-distance \
    --num-same-step 1 \
    --batch-size 8 \
    --test-freq 2 \
    --id 25 \
    --num-train-steps 6 \
    --resume